//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.08 at 06:11:12 PM ICT 
//


package demo_bean_util.demo_request_ap;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for biometricType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="biometricType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="Face"/>
 *     &lt;enumeration value="Fingerprint"/>
 *     &lt;enumeration value="Iris"/>
 *     &lt;enumeration value="Signature"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "biometricType")
@XmlEnum
public enum BiometricType {

    @XmlEnumValue("Face")
    FACE("Face"),
    @XmlEnumValue("Fingerprint")
    FINGERPRINT("Fingerprint"),
    @XmlEnumValue("Iris")
    IRIS("Iris"),
    @XmlEnumValue("Signature")
    SIGNATURE("Signature");
    private final String value;

    BiometricType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static BiometricType fromValue(String v) {
        for (BiometricType c: BiometricType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
