//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.08 at 06:11:12 PM ICT 
//


package demo_bean_util.demo_request_ap;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for biometricSourceType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="biometricSourceType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="Live"/>
 *     &lt;enumeration value="Document"/>
 *     &lt;enumeration value="Other"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "biometricSourceType")
@XmlEnum
public enum BiometricSourceType {

    @XmlEnumValue("Live")
    LIVE("Live"),
    @XmlEnumValue("Document")
    DOCUMENT("Document"),
    @XmlEnumValue("Other")
    OTHER("Other");
    private final String value;

    BiometricSourceType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static BiometricSourceType fromValue(String v) {
        for (BiometricSourceType c: BiometricSourceType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
