//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.08 at 06:10:55 PM ICT 
//


package demo_bean_util.demo_request_ap;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Check Manifest Status result type.
 * 
 * <p>Java class for CheckManifestStatusResultType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CheckManifestStatusResultType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="APPPassengerCount" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
 *         &lt;element name="APPCrewCount" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
 *         &lt;element name="ManifestPassengerCount" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
 *         &lt;element name="ManifestCrewCount" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
 *         &lt;element name="AdditionalInfo" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value=".{1,80}"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Error" type="{http://sita.aero/iborders/APP/common/V1}ErrorType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CheckManifestStatusResultType", namespace = "http://sita.aero/iborders/APP/APPService/V1", propOrder = {
    "appPassengerCount",
    "appCrewCount",
    "manifestPassengerCount",
    "manifestCrewCount",
    "additionalInfo",
    "error"
})
public class CheckManifestStatusResultType {

    @XmlElement(name = "APPPassengerCount")
    @XmlSchemaType(name = "unsignedShort")
    protected int appPassengerCount;
    @XmlElement(name = "APPCrewCount")
    @XmlSchemaType(name = "unsignedShort")
    protected int appCrewCount;
    @XmlElement(name = "ManifestPassengerCount")
    @XmlSchemaType(name = "unsignedShort")
    protected int manifestPassengerCount;
    @XmlElement(name = "ManifestCrewCount")
    @XmlSchemaType(name = "unsignedShort")
    protected int manifestCrewCount;
    @XmlElement(name = "AdditionalInfo")
    protected String additionalInfo;
    @XmlElement(name = "Error")
    protected List<ErrorType> error;

    /**
     * Gets the value of the appPassengerCount property.
     * 
     */
    public int getAPPPassengerCount() {
        return appPassengerCount;
    }

    /**
     * Sets the value of the appPassengerCount property.
     * 
     */
    public void setAPPPassengerCount(int value) {
        this.appPassengerCount = value;
    }

    /**
     * Gets the value of the appCrewCount property.
     * 
     */
    public int getAPPCrewCount() {
        return appCrewCount;
    }

    /**
     * Sets the value of the appCrewCount property.
     * 
     */
    public void setAPPCrewCount(int value) {
        this.appCrewCount = value;
    }

    /**
     * Gets the value of the manifestPassengerCount property.
     * 
     */
    public int getManifestPassengerCount() {
        return manifestPassengerCount;
    }

    /**
     * Sets the value of the manifestPassengerCount property.
     * 
     */
    public void setManifestPassengerCount(int value) {
        this.manifestPassengerCount = value;
    }

    /**
     * Gets the value of the manifestCrewCount property.
     * 
     */
    public int getManifestCrewCount() {
        return manifestCrewCount;
    }

    /**
     * Sets the value of the manifestCrewCount property.
     * 
     */
    public void setManifestCrewCount(int value) {
        this.manifestCrewCount = value;
    }

    /**
     * Gets the value of the additionalInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdditionalInfo() {
        return additionalInfo;
    }

    /**
     * Sets the value of the additionalInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdditionalInfo(String value) {
        this.additionalInfo = value;
    }

    /**
     * Gets the value of the error property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the error property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getError().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ErrorType }
     * 
     * 
     */
    public List<ErrorType> getError() {
        if (error == null) {
            error = new ArrayList<ErrorType>();
        }
        return this.error;
    }

}
