//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.08 at 06:10:55 PM ICT 
//


package demo_bean_util.demo_request_ap;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Traveller result type for check-in transaction.
 * 
 * <p>Java class for CheckInTravellerResultType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CheckInTravellerResultType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://sita.aero/iborders/APP/APPService/V1}TravellerResultType">
 *       &lt;sequence>
 *         &lt;element name="TravellerStatus" type="{http://sita.aero/iborders/APP/APPService/V1}checkInTravellerStatusType"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CheckInTravellerResultType", namespace = "http://sita.aero/iborders/APP/APPService/V1", propOrder = {
    "travellerStatus"
})
public class CheckInTravellerResultType
    extends TravellerResultType
{

    @XmlElement(name = "TravellerStatus", required = true)
    protected CheckInTravellerStatusType travellerStatus;

    /**
     * Gets the value of the travellerStatus property.
     * 
     * @return
     *     possible object is
     *     {@link CheckInTravellerStatusType }
     *     
     */
    public CheckInTravellerStatusType getTravellerStatus() {
        return travellerStatus;
    }

    /**
     * Sets the value of the travellerStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link CheckInTravellerStatusType }
     *     
     */
    public void setTravellerStatus(CheckInTravellerStatusType value) {
        this.travellerStatus = value;
    }

}
