//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.08 at 06:11:12 PM ICT 
//


package demo_bean_util.demo_request_ap;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Itinerary type.
 * 
 * <p>Java class for ItineraryType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ItineraryType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="OriginPort" type="{http://sita.aero/iborders/APP/common/V1}locationCodeType" minOccurs="0"/>
 *         &lt;element name="DestinationPort" type="{http://sita.aero/iborders/APP/common/V1}locationCodeType" minOccurs="0"/>
 *         &lt;element name="TransferAtOrigin" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="TransferAtDestination" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="JourneyInfo" type="{http://sita.aero/iborders/APP/common/V1}JourneyInfoType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ItineraryType", propOrder = {
    "originPort",
    "destinationPort",
    "transferAtOrigin",
    "transferAtDestination",
    "journeyInfo"
})
public class ItineraryType {

    @XmlElement(name = "OriginPort")
    protected String originPort;
    @XmlElement(name = "DestinationPort")
    protected String destinationPort;
    @XmlElement(name = "TransferAtOrigin")
    protected Boolean transferAtOrigin;
    @XmlElement(name = "TransferAtDestination")
    protected Boolean transferAtDestination;
    @XmlElement(name = "JourneyInfo")
    protected List<JourneyInfoType> journeyInfo;

    /**
     * Gets the value of the originPort property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginPort() {
        return originPort;
    }

    /**
     * Sets the value of the originPort property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginPort(String value) {
        this.originPort = value;
    }

    /**
     * Gets the value of the destinationPort property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDestinationPort() {
        return destinationPort;
    }

    /**
     * Sets the value of the destinationPort property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDestinationPort(String value) {
        this.destinationPort = value;
    }

    /**
     * Gets the value of the transferAtOrigin property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isTransferAtOrigin() {
        return transferAtOrigin;
    }

    /**
     * Sets the value of the transferAtOrigin property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setTransferAtOrigin(Boolean value) {
        this.transferAtOrigin = value;
    }

    /**
     * Gets the value of the transferAtDestination property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isTransferAtDestination() {
        return transferAtDestination;
    }

    /**
     * Sets the value of the transferAtDestination property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setTransferAtDestination(Boolean value) {
        this.transferAtDestination = value;
    }

    /**
     * Gets the value of the journeyInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the journeyInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getJourneyInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JourneyInfoType }
     * 
     * 
     */
    public List<JourneyInfoType> getJourneyInfo() {
        if (journeyInfo == null) {
            journeyInfo = new ArrayList<JourneyInfoType>();
        }
        return this.journeyInfo;
    }

}
