//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.08 at 06:11:12 PM ICT 
//


package demo_bean_util.demo_request_ap;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Journey type
 * 
 * The Journey Type represents a single flight.
 *         For flights scheduled with the OAG or manually added, then the minimum of    details required are:
 *         - Departure Port
 *         - Arrival Port
 *         - Departure Date
 *         - Service Number
 *         For Unscheduled Flights, the previous are still required but each leg/segment of the flight will need to be specified in the JourneyInfo list of elements.
 *         If no check in details are given, these will be assumed to be either the expected origin (if given) or the departure port of the journey.  
 * 
 * <p>Java class for JourneyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="JourneyType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ScheduleType" type="{http://sita.aero/iborders/APP/common/V1}journeyScheduleType" minOccurs="0"/>
 *         &lt;element name="CarrierType" type="{http://sita.aero/iborders/APP/common/V1}carrierType" minOccurs="0"/>
 *         &lt;element name="CarrierCode" type="{http://sita.aero/iborders/APP/common/V1}carrierCodeType" minOccurs="0"/>
 *         &lt;element name="ServiceNumber" type="{http://sita.aero/iborders/APP/common/V1}serviceNumberType"/>
 *         &lt;element name="DeparturePort" type="{http://sita.aero/iborders/APP/common/V1}locationCodeType"/>
 *         &lt;element name="ArrivalPort" type="{http://sita.aero/iborders/APP/common/V1}locationCodeType"/>
 *         &lt;element name="DepartureDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="CheckInInfo" type="{http://sita.aero/iborders/APP/common/V1}ServiceTransactionInfoType" minOccurs="0"/>
 *         &lt;element name="ExpectedOriginInfo" type="{http://sita.aero/iborders/APP/common/V1}ServiceTransactionInfoType" minOccurs="0"/>
 *         &lt;element name="JourneyInfo" type="{http://sita.aero/iborders/APP/common/V1}JourneyInfoType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ExpectedDestinationInfo" type="{http://sita.aero/iborders/APP/common/V1}ServiceTransactionInfoType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "JourneyType", propOrder = {
    "scheduleType",
    "carrierType",
    "carrierCode",
    "serviceNumber",
    "departurePort",
    "arrivalPort",
    "departureDate",
    "checkInInfo",
    "expectedOriginInfo",
    "journeyInfo",
    "expectedDestinationInfo"
})
public class JourneyType {

    @XmlElement(name = "ScheduleType")
    protected JourneyScheduleType scheduleType;
    @XmlElement(name = "CarrierType")
    protected CarrierType carrierType;
    @XmlElement(name = "CarrierCode")
    protected String carrierCode;
    @XmlElement(name = "ServiceNumber", required = true)
    protected String serviceNumber;
    @XmlElement(name = "DeparturePort", required = true)
    protected String departurePort;
    @XmlElement(name = "ArrivalPort", required = true)
    protected String arrivalPort;
    @XmlElement(name = "DepartureDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar departureDate;
    @XmlElement(name = "CheckInInfo")
    protected ServiceTransactionInfoType checkInInfo;
    @XmlElement(name = "ExpectedOriginInfo")
    protected ServiceTransactionInfoType expectedOriginInfo;
    @XmlElement(name = "JourneyInfo")
    protected List<JourneyInfoType> journeyInfo;
    @XmlElement(name = "ExpectedDestinationInfo")
    protected ServiceTransactionInfoType expectedDestinationInfo;

    /**
     * Gets the value of the scheduleType property.
     * 
     * @return
     *     possible object is
     *     {@link JourneyScheduleType }
     *     
     */
    public JourneyScheduleType getScheduleType() {
        return scheduleType;
    }

    /**
     * Sets the value of the scheduleType property.
     * 
     * @param value
     *     allowed object is
     *     {@link JourneyScheduleType }
     *     
     */
    public void setScheduleType(JourneyScheduleType value) {
        this.scheduleType = value;
    }

    /**
     * Gets the value of the carrierType property.
     * 
     * @return
     *     possible object is
     *     {@link CarrierType }
     *     
     */
    public CarrierType getCarrierType() {
        return carrierType;
    }

    /**
     * Sets the value of the carrierType property.
     * 
     * @param value
     *     allowed object is
     *     {@link CarrierType }
     *     
     */
    public void setCarrierType(CarrierType value) {
        this.carrierType = value;
    }

    /**
     * Gets the value of the carrierCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCarrierCode() {
        return carrierCode;
    }

    /**
     * Sets the value of the carrierCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCarrierCode(String value) {
        this.carrierCode = value;
    }

    /**
     * Gets the value of the serviceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceNumber() {
        return serviceNumber;
    }

    /**
     * Sets the value of the serviceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceNumber(String value) {
        this.serviceNumber = value;
    }

    /**
     * Gets the value of the departurePort property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeparturePort() {
        return departurePort;
    }

    /**
     * Sets the value of the departurePort property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeparturePort(String value) {
        this.departurePort = value;
    }

    /**
     * Gets the value of the arrivalPort property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArrivalPort() {
        return arrivalPort;
    }

    /**
     * Sets the value of the arrivalPort property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArrivalPort(String value) {
        this.arrivalPort = value;
    }

    /**
     * Gets the value of the departureDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDepartureDate() {
        return departureDate;
    }

    /**
     * Sets the value of the departureDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDepartureDate(XMLGregorianCalendar value) {
        this.departureDate = value;
    }

    /**
     * Gets the value of the checkInInfo property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceTransactionInfoType }
     *     
     */
    public ServiceTransactionInfoType getCheckInInfo() {
        return checkInInfo;
    }

    /**
     * Sets the value of the checkInInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceTransactionInfoType }
     *     
     */
    public void setCheckInInfo(ServiceTransactionInfoType value) {
        this.checkInInfo = value;
    }

    /**
     * Gets the value of the expectedOriginInfo property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceTransactionInfoType }
     *     
     */
    public ServiceTransactionInfoType getExpectedOriginInfo() {
        return expectedOriginInfo;
    }

    /**
     * Sets the value of the expectedOriginInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceTransactionInfoType }
     *     
     */
    public void setExpectedOriginInfo(ServiceTransactionInfoType value) {
        this.expectedOriginInfo = value;
    }

    /**
     * Gets the value of the journeyInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the journeyInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getJourneyInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JourneyInfoType }
     * 
     * 
     */
    public List<JourneyInfoType> getJourneyInfo() {
        if (journeyInfo == null) {
            journeyInfo = new ArrayList<JourneyInfoType>();
        }
        return this.journeyInfo;
    }

    /**
     * Gets the value of the expectedDestinationInfo property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceTransactionInfoType }
     *     
     */
    public ServiceTransactionInfoType getExpectedDestinationInfo() {
        return expectedDestinationInfo;
    }

    /**
     * Sets the value of the expectedDestinationInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceTransactionInfoType }
     *     
     */
    public void setExpectedDestinationInfo(ServiceTransactionInfoType value) {
        this.expectedDestinationInfo = value;
    }

	public void setJourneyInfo(List<JourneyInfoType> journeyInfo) {
		this.journeyInfo = journeyInfo;
	}
    
}
