//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.08 at 06:10:55 PM ICT 
//


package demo_bean_util.demo_request_ap;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Non-traveller result type for request gate pass transaction.
 * 
 * <p>Java class for NonTravellerResultType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NonTravellerResultType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://sita.aero/iborders/APP/APPService/V1}TravellerResultType">
 *       &lt;sequence>
 *         &lt;element name="NonTravellerStatus" type="{http://sita.aero/iborders/APP/APPService/V1}nonTravellerStatusType"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NonTravellerResultType", namespace = "http://sita.aero/iborders/APP/APPService/V1", propOrder = {
    "nonTravellerStatus"
})
public class NonTravellerResultType
    extends TravellerResultType
{

    @XmlElement(name = "NonTravellerStatus", required = true)
    protected NonTravellerStatusType nonTravellerStatus;

    /**
     * Gets the value of the nonTravellerStatus property.
     * 
     * @return
     *     possible object is
     *     {@link NonTravellerStatusType }
     *     
     */
    public NonTravellerStatusType getNonTravellerStatus() {
        return nonTravellerStatus;
    }

    /**
     * Sets the value of the nonTravellerStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link NonTravellerStatusType }
     *     
     */
    public void setNonTravellerStatus(NonTravellerStatusType value) {
        this.nonTravellerStatus = value;
    }

}
