//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.08 at 06:10:55 PM ICT 
//


package demo_bean_util.demo_request_ap;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Notify Service Event request type.
 * 
 * <p>Java class for NotifyServiceEventRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NotifyServiceEventRequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Header" type="{http://sita.aero/iborders/APP/APPService/V1}SpecificCountryHeaderType"/>
 *         &lt;element name="Journey" type="{http://sita.aero/iborders/APP/common/V1}JourneyType"/>
 *         &lt;element name="PassengerManifestRequest" type="{http://sita.aero/iborders/APP/APPService/V1}manifestRequirementType"/>
 *         &lt;element name="CrewManifestRequest" type="{http://sita.aero/iborders/APP/APPService/V1}manifestRequirementType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NotifyServiceEventRequestType", namespace = "http://sita.aero/iborders/APP/APPService/V1", propOrder = {
    "header",
    "journey",
    "passengerManifestRequest",
    "crewManifestRequest"
})
@XmlRootElement(name = "NotifyServiceEventRequest", namespace = "http://sita.aero/iborders/APP/APPService/V1")
public class NotifyServiceEventRequestType {

    @XmlElement(name = "Header", required = true)
    protected SpecificCountryHeaderType header;
    @XmlElement(name = "Journey", required = true)
    protected JourneyType journey;
    @XmlElement(name = "PassengerManifestRequest", required = true)
    protected ManifestRequirementType passengerManifestRequest;
    @XmlElement(name = "CrewManifestRequest", required = true)
    protected ManifestRequirementType crewManifestRequest;

    /**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link SpecificCountryHeaderType }
     *     
     */
    public SpecificCountryHeaderType getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpecificCountryHeaderType }
     *     
     */
    public void setHeader(SpecificCountryHeaderType value) {
        this.header = value;
    }

    /**
     * Gets the value of the journey property.
     * 
     * @return
     *     possible object is
     *     {@link JourneyType }
     *     
     */
    public JourneyType getJourney() {
        return journey;
    }

    /**
     * Sets the value of the journey property.
     * 
     * @param value
     *     allowed object is
     *     {@link JourneyType }
     *     
     */
    public void setJourney(JourneyType value) {
        this.journey = value;
    }

    /**
     * Gets the value of the passengerManifestRequest property.
     * 
     * @return
     *     possible object is
     *     {@link ManifestRequirementType }
     *     
     */
    public ManifestRequirementType getPassengerManifestRequest() {
        return passengerManifestRequest;
    }

    /**
     * Sets the value of the passengerManifestRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link ManifestRequirementType }
     *     
     */
    public void setPassengerManifestRequest(ManifestRequirementType value) {
        this.passengerManifestRequest = value;
    }

    /**
     * Gets the value of the crewManifestRequest property.
     * 
     * @return
     *     possible object is
     *     {@link ManifestRequirementType }
     *     
     */
    public ManifestRequirementType getCrewManifestRequest() {
        return crewManifestRequest;
    }

    /**
     * Sets the value of the crewManifestRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link ManifestRequirementType }
     *     
     */
    public void setCrewManifestRequest(ManifestRequirementType value) {
        this.crewManifestRequest = value;
    }

}
