//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.08 at 06:11:12 PM ICT 
//


package demo_bean_util.demo_request_ap;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.cct.app.core.mq.validate.domain package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.cct.app.core.mq.validate.domain
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ErrorType }
     * 
     */
    public ErrorType createErrorType() {
        return new ErrorType();
    }

    /**
     * Create an instance of {@link ServiceTransactionInfoType }
     * 
     */
    public ServiceTransactionInfoType createServiceTransactionInfoType() {
        return new ServiceTransactionInfoType();
    }

    /**
     * Create an instance of {@link ItineraryType }
     * 
     */
    public ItineraryType createItineraryType() {
        return new ItineraryType();
    }

    /**
     * Create an instance of {@link PNRType }
     * 
     */
    public PNRType createPNRType() {
        return new PNRType();
    }

    /**
     * Create an instance of {@link PlaceOfBirthType }
     * 
     */
    public PlaceOfBirthType createPlaceOfBirthType() {
        return new PlaceOfBirthType();
    }

    /**
     * Create an instance of {@link TravelDocumentType }
     * 
     */
    public TravelDocumentType createTravelDocumentType() {
        return new TravelDocumentType();
    }

    /**
     * Create an instance of {@link JourneyInfoType }
     * 
     */
    public JourneyInfoType createJourneyInfoType() {
        return new JourneyInfoType();
    }

    /**
     * Create an instance of {@link FrequentFlyerType }
     * 
     */
    public FrequentFlyerType createFrequentFlyerType() {
        return new FrequentFlyerType();
    }

    /**
     * Create an instance of {@link TimingInfoType }
     * 
     */
    public TimingInfoType createTimingInfoType() {
        return new TimingInfoType();
    }

    /**
     * Create an instance of {@link CheckResultType }
     * 
     */
    public CheckResultType createCheckResultType() {
        return new CheckResultType();
    }

    /**
     * Create an instance of {@link BagType }
     * 
     */
    public BagType createBagType() {
        return new BagType();
    }

    /**
     * Create an instance of {@link TravellerInfoType }
     * 
     */
    public TravellerInfoType createTravellerInfoType() {
        return new TravellerInfoType();
    }

    /**
     * Create an instance of {@link TravellerType }
     * 
     */
    public TravellerType createTravellerType() {
        return new TravellerType();
    }

    /**
     * Create an instance of {@link FaultType }
     * 
     */
    public FaultType createFaultType() {
        return new FaultType();
    }

    /**
     * Create an instance of {@link BoardingPassType }
     * 
     */
    public BoardingPassType createBoardingPassType() {
        return new BoardingPassType();
    }

    /**
     * Create an instance of {@link AgencyType }
     * 
     */
    public AgencyType createAgencyType() {
        return new AgencyType();
    }

    /**
     * Create an instance of {@link KeyValueType }
     * 
     */
    public KeyValueType createKeyValueType() {
        return new KeyValueType();
    }

    /**
     * Create an instance of {@link IdentityType }
     * 
     */
    public IdentityType createIdentityType() {
        return new IdentityType();
    }

    /**
     * Create an instance of {@link OverrideType }
     * 
     */
    public OverrideType createOverrideType() {
        return new OverrideType();
    }

    /**
     * Create an instance of {@link JourneyType }
     * 
     */
    public JourneyType createJourneyType() {
        return new JourneyType();
    }

    /**
     * Create an instance of {@link AddressType }
     * 
     */
    public AddressType createAddressType() {
        return new AddressType();
    }

    /**
     * Create an instance of {@link BiometricDataType }
     * 
     */
    public BiometricDataType createBiometricDataType() {
        return new BiometricDataType();
    }

}
