//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.08 at 06:11:12 PM ICT 
//

@javax.xml.bind.annotation.XmlSchema( 
namespace = "http://sita.aero/iborders/APP/common/V1", 
    xmlns = { 
          @javax.xml.bind.annotation.XmlNs(prefix = "app", namespaceURI = "http://sita.aero/iborders/APP/APPService/V1"), 
          @javax.xml.bind.annotation.XmlNs(prefix = "com", namespaceURI = "http://sita.aero/iborders/APP/common/V1"), 
          @javax.xml.bind.annotation.XmlNs(prefix = "xsi", namespaceURI = "http://www.w3.org/2001/XMLSchema-instance") 
            },  
    elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED) 
package demo_bean_util.demo_request_ap;
