//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.08 at 06:10:55 PM ICT 
//


package demo_bean_util.demo_request_ap;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Request Gate Pass request type.
 * 
 * <p>Java class for RequestGatePassRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RequestGatePassRequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Header" type="{http://sita.aero/iborders/APP/APPService/V1}SpecificCountryHeaderType"/>
 *         &lt;element name="LocationDetails" type="{http://sita.aero/iborders/APP/APPService/V1}GatePassRequestDetailsType"/>
 *         &lt;element name="NonTraveller" type="{http://sita.aero/iborders/APP/common/V1}TravellerType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RequestGatePassRequestType", namespace = "http://sita.aero/iborders/APP/APPService/V1", propOrder = {
    "header",
    "locationDetails",
    "nonTraveller"
})
public class RequestGatePassRequestType {

    @XmlElement(name = "Header", required = true)
    protected SpecificCountryHeaderType header;
    @XmlElement(name = "LocationDetails", required = true)
    protected GatePassRequestDetailsType locationDetails;
    @XmlElement(name = "NonTraveller", required = true)
    protected List<TravellerType> nonTraveller;

    /**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link SpecificCountryHeaderType }
     *     
     */
    public SpecificCountryHeaderType getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpecificCountryHeaderType }
     *     
     */
    public void setHeader(SpecificCountryHeaderType value) {
        this.header = value;
    }

    /**
     * Gets the value of the locationDetails property.
     * 
     * @return
     *     possible object is
     *     {@link GatePassRequestDetailsType }
     *     
     */
    public GatePassRequestDetailsType getLocationDetails() {
        return locationDetails;
    }

    /**
     * Sets the value of the locationDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link GatePassRequestDetailsType }
     *     
     */
    public void setLocationDetails(GatePassRequestDetailsType value) {
        this.locationDetails = value;
    }

    /**
     * Gets the value of the nonTraveller property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nonTraveller property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNonTraveller().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TravellerType }
     * 
     * 
     */
    public List<TravellerType> getNonTraveller() {
        if (nonTraveller == null) {
            nonTraveller = new ArrayList<TravellerType>();
        }
        return this.nonTraveller;
    }

}
