//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.08 at 06:10:55 PM ICT 
//


package demo_bean_util.demo_request_ap;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * System error type.
 * 
 * <p>Java class for SystemErrorType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SystemErrorType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://sita.aero/iborders/APP/common/V1}ErrorType">
 *       &lt;sequence>
 *         &lt;element name="ParticipatingCountry" type="{http://sita.aero/iborders/APP/common/V1}countryCodeType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SystemErrorType", namespace = "http://sita.aero/iborders/APP/APPService/V1", propOrder = {
    "participatingCountry"
})
public class SystemErrorType
    extends ErrorType
{

    @XmlElement(name = "ParticipatingCountry")
    protected String participatingCountry;

    /**
     * Gets the value of the participatingCountry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParticipatingCountry() {
        return participatingCountry;
    }

    /**
     * Sets the value of the participatingCountry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParticipatingCountry(String value) {
        this.participatingCountry = value;
    }

}
