//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.08 at 06:11:12 PM ICT 
//


package demo_bean_util.demo_request_ap;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Traveller type.
 * 
 * <p>Java class for TravellerType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TravellerType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TravellerInfo" type="{http://sita.aero/iborders/APP/common/V1}TravellerInfoType"/>
 *         &lt;element name="Identity" type="{http://sita.aero/iborders/APP/common/V1}IdentityType"/>
 *         &lt;element name="BoardingPass" type="{http://sita.aero/iborders/APP/common/V1}BoardingPassType" minOccurs="0"/>
 *         &lt;element name="PNR" type="{http://sita.aero/iborders/APP/common/V1}PNRType" minOccurs="0"/>
 *         &lt;element name="Itinerary" type="{http://sita.aero/iborders/APP/common/V1}ItineraryType" minOccurs="0"/>
 *         &lt;element name="OverrideCode" type="{http://sita.aero/iborders/APP/common/V1}OverrideType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TravellerType", propOrder = {
    "travellerInfo",
    "identity",
    "boardingPass",
    "pnr",
    "itinerary",
    "overrideCode"
})
public class TravellerType {

    @XmlElement(name = "TravellerInfo", required = true)
    protected TravellerInfoType travellerInfo;
    @XmlElement(name = "Identity", required = true)
    protected IdentityType identity;
    @XmlElement(name = "BoardingPass")
    protected BoardingPassType boardingPass;
    @XmlElement(name = "PNR")
    protected PNRType pnr;
    @XmlElement(name = "Itinerary")
    protected ItineraryType itinerary;
    @XmlElement(name = "OverrideCode")
    protected List<OverrideType> overrideCode;

    /**
     * Gets the value of the travellerInfo property.
     * 
     * @return
     *     possible object is
     *     {@link TravellerInfoType }
     *     
     */
    public TravellerInfoType getTravellerInfo() {
        return travellerInfo;
    }

    /**
     * Sets the value of the travellerInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link TravellerInfoType }
     *     
     */
    public void setTravellerInfo(TravellerInfoType value) {
        this.travellerInfo = value;
    }

    /**
     * Gets the value of the identity property.
     * 
     * @return
     *     possible object is
     *     {@link IdentityType }
     *     
     */
    public IdentityType getIdentity() {
        return identity;
    }

    /**
     * Sets the value of the identity property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentityType }
     *     
     */
    public void setIdentity(IdentityType value) {
        this.identity = value;
    }

    /**
     * Gets the value of the boardingPass property.
     * 
     * @return
     *     possible object is
     *     {@link BoardingPassType }
     *     
     */
    public BoardingPassType getBoardingPass() {
        return boardingPass;
    }

    /**
     * Sets the value of the boardingPass property.
     * 
     * @param value
     *     allowed object is
     *     {@link BoardingPassType }
     *     
     */
    public void setBoardingPass(BoardingPassType value) {
        this.boardingPass = value;
    }

    /**
     * Gets the value of the pnr property.
     * 
     * @return
     *     possible object is
     *     {@link PNRType }
     *     
     */
    public PNRType getPNR() {
        return pnr;
    }

    /**
     * Sets the value of the pnr property.
     * 
     * @param value
     *     allowed object is
     *     {@link PNRType }
     *     
     */
    public void setPNR(PNRType value) {
        this.pnr = value;
    }

    /**
     * Gets the value of the itinerary property.
     * 
     * @return
     *     possible object is
     *     {@link ItineraryType }
     *     
     */
    public ItineraryType getItinerary() {
        return itinerary;
    }

    /**
     * Sets the value of the itinerary property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItineraryType }
     *     
     */
    public void setItinerary(ItineraryType value) {
        this.itinerary = value;
    }

    /**
     * Gets the value of the overrideCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the overrideCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOverrideCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OverrideType }
     * 
     * 
     */
    public List<OverrideType> getOverrideCode() {
        if (overrideCode == null) {
            overrideCode = new ArrayList<OverrideType>();
        }
        return this.overrideCode;
    }

	public PNRType getPnr() {
		return pnr;
	}

	public void setPnr(PNRType pnr) {
		this.pnr = pnr;
	}

	public void setOverrideCode(List<OverrideType> overrideCode) {
		this.overrideCode = overrideCode;
	}
    
    

}
